/**
 * V17 PROSODIC BEAT REGISTRY
 * 
 * Maps all 23 semantic beats of the Persian Editorial film to their acoustic prosodic profile
 * and resulting motion choreography parameters.
 */

import { ProsodicBeat } from './prosodicBeatTypes';

export const PROSODIC_BEATS: ProsodicBeat[] = [
  // ==================== SHOT 01: THE HOOK ====================
  {
    id: 'prosody_01_intro_attribution',
    semanticBeatId: 'beat_01_presenter_intro',
    shotId: 'Shot01',
    startFrame: 0,
    endFrame: 165,
    vocalStress: 'secondary-stress',
    pitchContour: 'peaking-declarative',
    speechCadence: 'legato',
    pausePreRollFrames: 0,
    pausePostRollFrames: 19, // ~0.63s pause before question
    anticipationFrames: 12,
    settleDamping: 0.85,
    scalePeakMultiplier: 1.05,
    velocityRamp: 'smooth-ease',
    materialResponse: {
      rimLightIntensity: 0.45,
      depthShadowBlur: 18,
      frostedBlurPx: 16,
    },
  },
  {
    id: 'prosody_02_question_lead',
    semanticBeatId: 'beat_02_hook_question_lead',
    shotId: 'Shot01',
    startFrame: 165,
    endFrame: 230,
    vocalStress: 'unstressed',
    pitchContour: 'rising-interrogative',
    speechCadence: 'accelerando',
    pausePreRollFrames: 19,
    pausePostRollFrames: 4,
    anticipationFrames: 8,
    settleDamping: 0.80,
    scalePeakMultiplier: 1.04,
    velocityRamp: 'delayed-spring',
    materialResponse: {
      rimLightIntensity: 0.35,
      depthShadowBlur: 14,
      frostedBlurPx: 14,
    },
  },
  {
    id: 'prosody_03_keyword_strike',
    semanticBeatId: 'beat_03_hero_keyword_strike',
    shotId: 'Shot01',
    startFrame: 230,
    endFrame: 350,
    vocalStress: 'primary-stress',
    pitchContour: 'peaking-declarative',
    speechCadence: 'staccato',
    pausePreRollFrames: 4,
    pausePostRollFrames: 15,
    anticipationFrames: 14,
    settleDamping: 0.72,
    scalePeakMultiplier: 1.15,
    velocityRamp: 'sharp-snap',
    materialResponse: {
      rimLightIntensity: 0.75,
      depthShadowBlur: 24,
      frostedBlurPx: 20,
    },
  },
  {
    id: 'prosody_04_t1_handoff',
    semanticBeatId: 'beat_04_t1_underline_handoff',
    shotId: 'Shot01',
    startFrame: 350,
    endFrame: 380,
    vocalStress: 'pause-cadence',
    pitchContour: 'sustained-steady',
    speechCadence: 'legato',
    pausePreRollFrames: 15,
    pausePostRollFrames: 0,
    anticipationFrames: 10,
    settleDamping: 0.90,
    scalePeakMultiplier: 1.02,
    velocityRamp: 'smooth-ease',
    materialResponse: {
      rimLightIntensity: 0.60,
      depthShadowBlur: 20,
      frostedBlurPx: 18,
    },
  },

  // ==================== SHOT 02: THE DECREE ====================
  {
    id: 'prosody_05_statute_collision',
    semanticBeatId: 'beat_05_statute_collision',
    shotId: 'Shot02',
    startFrame: 380,
    endFrame: 480,
    vocalStress: 'primary-stress',
    pitchContour: 'peaking-declarative',
    speechCadence: 'staccato',
    pausePreRollFrames: 10,
    pausePostRollFrames: 8,
    anticipationFrames: 15,
    settleDamping: 0.75,
    scalePeakMultiplier: 1.12,
    velocityRamp: 'sharp-snap',
    materialResponse: {
      rimLightIntensity: 0.70,
      depthShadowBlur: 26,
      frostedBlurPx: 22,
    },
  },
  {
    id: 'prosody_06_decree_path',
    semanticBeatId: 'beat_06_decree_source_path',
    shotId: 'Shot02',
    startFrame: 480,
    endFrame: 620,
    vocalStress: 'unstressed',
    pitchContour: 'falling-cadence',
    speechCadence: 'legato',
    pausePreRollFrames: 8,
    pausePostRollFrames: 24,
    anticipationFrames: 10,
    settleDamping: 0.88,
    scalePeakMultiplier: 1.03,
    velocityRamp: 'smooth-ease',
    materialResponse: {
      rimLightIntensity: 0.40,
      depthShadowBlur: 16,
      frostedBlurPx: 16,
    },
  },
  {
    id: 'prosody_07_t2_fission',
    semanticBeatId: 'beat_07_t2_symmetric_fission',
    shotId: 'Shot02',
    startFrame: 620,
    endFrame: 650,
    vocalStress: 'pause-cadence',
    pitchContour: 'sustained-steady',
    speechCadence: 'legato',
    pausePreRollFrames: 24,
    pausePostRollFrames: 4,
    anticipationFrames: 12,
    settleDamping: 0.85,
    scalePeakMultiplier: 1.06,
    velocityRamp: 'delayed-spring',
    materialResponse: {
      rimLightIntensity: 0.55,
      depthShadowBlur: 22,
      frostedBlurPx: 18,
    },
  },

  // ==================== SHOT 03: CRITERIA ====================
  {
    id: 'prosody_08_criteria_header',
    semanticBeatId: 'beat_08_criteria_section_header',
    shotId: 'Shot03',
    startFrame: 650,
    endFrame: 750,
    vocalStress: 'secondary-stress',
    pitchContour: 'peaking-declarative',
    speechCadence: 'ritardando',
    pausePreRollFrames: 4,
    pausePostRollFrames: 12,
    anticipationFrames: 10,
    settleDamping: 0.82,
    scalePeakMultiplier: 1.05,
    velocityRamp: 'smooth-ease',
    materialResponse: {
      rimLightIntensity: 0.50,
      depthShadowBlur: 20,
      frostedBlurPx: 16,
    },
  },
  {
    id: 'prosody_09_c1_gpa',
    semanticBeatId: 'beat_09_criterion1_gpa_lock',
    shotId: 'Shot03',
    startFrame: 750,
    endFrame: 950,
    vocalStress: 'primary-stress',
    pitchContour: 'peaking-declarative',
    speechCadence: 'staccato',
    pausePreRollFrames: 12,
    pausePostRollFrames: 10,
    anticipationFrames: 14,
    settleDamping: 0.74,
    scalePeakMultiplier: 1.14,
    velocityRamp: 'sharp-snap',
    materialResponse: {
      rimLightIntensity: 0.75,
      depthShadowBlur: 25,
      frostedBlurPx: 20,
    },
  },
  {
    id: 'prosody_10_c2_disciplinary',
    semanticBeatId: 'beat_10_criterion2_disciplinary_lock',
    shotId: 'Shot03',
    startFrame: 950,
    endFrame: 1150,
    vocalStress: 'primary-stress',
    pitchContour: 'peaking-declarative',
    speechCadence: 'staccato',
    pausePreRollFrames: 10,
    pausePostRollFrames: 12,
    anticipationFrames: 14,
    settleDamping: 0.74,
    scalePeakMultiplier: 1.14,
    velocityRamp: 'sharp-snap',
    materialResponse: {
      rimLightIntensity: 0.75,
      depthShadowBlur: 25,
      frostedBlurPx: 20,
    },
  },
  {
    id: 'prosody_11_c3_articles',
    semanticBeatId: 'beat_11_criterion3_articles_lock',
    shotId: 'Shot03',
    startFrame: 1150,
    endFrame: 1450,
    vocalStress: 'primary-stress',
    pitchContour: 'peaking-declarative',
    speechCadence: 'legato',
    pausePreRollFrames: 12,
    pausePostRollFrames: 20,
    anticipationFrames: 14,
    settleDamping: 0.76,
    scalePeakMultiplier: 1.12,
    velocityRamp: 'sharp-snap',
    materialResponse: {
      rimLightIntensity: 0.70,
      depthShadowBlur: 24,
      frostedBlurPx: 20,
    },
  },
  {
    id: 'prosody_12_t3_collapse',
    semanticBeatId: 'beat_12_t3_axis_collapse',
    shotId: 'Shot03',
    startFrame: 1450,
    endFrame: 1480,
    vocalStress: 'pause-cadence',
    pitchContour: 'sustained-steady',
    speechCadence: 'legato',
    pausePreRollFrames: 20,
    pausePostRollFrames: 0,
    anticipationFrames: 10,
    settleDamping: 0.88,
    scalePeakMultiplier: 1.03,
    velocityRamp: 'smooth-ease',
    materialResponse: {
      rimLightIntensity: 0.50,
      depthShadowBlur: 20,
      frostedBlurPx: 16,
    },
  },

  // ==================== SHOT 04: TIME WINDOW ====================
  {
    id: 'prosody_13_timeline_travel',
    semanticBeatId: 'beat_13_timeline_chronological_travel',
    shotId: 'Shot04',
    startFrame: 1480,
    endFrame: 1550,
    vocalStress: 'secondary-stress',
    pitchContour: 'sustained-steady',
    speechCadence: 'accelerando',
    pausePreRollFrames: 0,
    pausePostRollFrames: 6,
    anticipationFrames: 8,
    settleDamping: 0.84,
    scalePeakMultiplier: 1.05,
    velocityRamp: 'delayed-spring',
    materialResponse: {
      rimLightIntensity: 0.45,
      depthShadowBlur: 18,
      frostedBlurPx: 16,
    },
  },
  {
    id: 'prosody_14_barrier_collision',
    semanticBeatId: 'beat_14_cutoff_barrier_collision',
    shotId: 'Shot04',
    startFrame: 1550,
    endFrame: 1700,
    vocalStress: 'primary-stress',
    pitchContour: 'peaking-declarative',
    speechCadence: 'staccato',
    pausePreRollFrames: 6,
    pausePostRollFrames: 15,
    anticipationFrames: 16,
    settleDamping: 0.70,
    scalePeakMultiplier: 1.18,
    velocityRamp: 'sharp-snap',
    materialResponse: {
      rimLightIntensity: 0.85,
      depthShadowBlur: 28,
      frostedBlurPx: 22,
    },
  },
  {
    id: 'prosody_15_t4_stage_fold',
    semanticBeatId: 'beat_15_t4_planar_stage_fold',
    shotId: 'Shot04',
    startFrame: 1700,
    endFrame: 1730,
    vocalStress: 'pause-cadence',
    pitchContour: 'sustained-steady',
    speechCadence: 'legato',
    pausePreRollFrames: 15,
    pausePostRollFrames: 0,
    anticipationFrames: 10,
    settleDamping: 0.88,
    scalePeakMultiplier: 1.03,
    velocityRamp: 'smooth-ease',
    materialResponse: {
      rimLightIntensity: 0.55,
      depthShadowBlur: 20,
      frostedBlurPx: 18,
    },
  },

  // ==================== SHOT 05: THRESHOLDS ====================
  {
    id: 'prosody_16_thresholds_intro',
    semanticBeatId: 'beat_16_thresholds_section_intro',
    shotId: 'Shot05',
    startFrame: 1730,
    endFrame: 1880,
    vocalStress: 'secondary-stress',
    pitchContour: 'peaking-declarative',
    speechCadence: 'ritardando',
    pausePreRollFrames: 0,
    pausePostRollFrames: 10,
    anticipationFrames: 12,
    settleDamping: 0.82,
    scalePeakMultiplier: 1.06,
    velocityRamp: 'smooth-ease',
    materialResponse: {
      rimLightIntensity: 0.50,
      depthShadowBlur: 20,
      frostedBlurPx: 18,
    },
  },
  {
    id: 'prosody_17_tier1_bachelor',
    semanticBeatId: 'beat_17_tier1_bachelor_65',
    shotId: 'Shot05',
    startFrame: 1880,
    endFrame: 1980,
    vocalStress: 'primary-stress',
    pitchContour: 'peaking-declarative',
    speechCadence: 'staccato',
    pausePreRollFrames: 10,
    pausePostRollFrames: 8,
    anticipationFrames: 12,
    settleDamping: 0.75,
    scalePeakMultiplier: 1.10,
    velocityRamp: 'sharp-snap',
    materialResponse: {
      rimLightIntensity: 0.70,
      depthShadowBlur: 24,
      frostedBlurPx: 20,
    },
  },
  {
    id: 'prosody_18_tier2_medicine',
    semanticBeatId: 'beat_18_tier2_medicine_110',
    shotId: 'Shot05',
    startFrame: 1980,
    endFrame: 2070,
    vocalStress: 'primary-stress',
    pitchContour: 'peaking-declarative',
    speechCadence: 'staccato',
    pausePreRollFrames: 8,
    pausePostRollFrames: 8,
    anticipationFrames: 12,
    settleDamping: 0.75,
    scalePeakMultiplier: 1.12,
    velocityRamp: 'sharp-snap',
    materialResponse: {
      rimLightIntensity: 0.75,
      depthShadowBlur: 26,
      frostedBlurPx: 22,
    },
  },
  {
    id: 'prosody_19_tier3_phd',
    semanticBeatId: 'beat_19_tier3_phd_130',
    shotId: 'Shot05',
    startFrame: 2070,
    endFrame: 2155,
    vocalStress: 'primary-stress',
    pitchContour: 'peaking-declarative',
    speechCadence: 'staccato',
    pausePreRollFrames: 8,
    pausePostRollFrames: 12,
    anticipationFrames: 14,
    settleDamping: 0.72,
    scalePeakMultiplier: 1.15,
    velocityRamp: 'sharp-snap',
    materialResponse: {
      rimLightIntensity: 0.85,
      depthShadowBlur: 30,
      frostedBlurPx: 24,
    },
  },
  {
    id: 'prosody_20_t5_singularity',
    semanticBeatId: 'beat_20_t5_gravitational_singularity',
    shotId: 'Shot05',
    startFrame: 2155,
    endFrame: 2185,
    vocalStress: 'pause-cadence',
    pitchContour: 'sustained-steady',
    speechCadence: 'legato',
    pausePreRollFrames: 12,
    pausePostRollFrames: 0,
    anticipationFrames: 12,
    settleDamping: 0.86,
    scalePeakMultiplier: 1.04,
    velocityRamp: 'delayed-spring',
    materialResponse: {
      rimLightIntensity: 0.65,
      depthShadowBlur: 22,
      frostedBlurPx: 20,
    },
  },

  // ==================== SHOT 06: OUTRO ====================
  {
    id: 'prosody_21_crest_reveal',
    semanticBeatId: 'beat_21_heraldic_crest_reveal',
    shotId: 'Shot06',
    startFrame: 2185,
    endFrame: 2260,
    vocalStress: 'primary-stress',
    pitchContour: 'peaking-declarative',
    speechCadence: 'legato',
    pausePreRollFrames: 0,
    pausePostRollFrames: 8,
    anticipationFrames: 15,
    settleDamping: 0.76,
    scalePeakMultiplier: 1.12,
    velocityRamp: 'sharp-snap',
    materialResponse: {
      rimLightIntensity: 0.80,
      depthShadowBlur: 28,
      frostedBlurPx: 22,
    },
  },
  {
    id: 'prosody_22_outro_continuation',
    semanticBeatId: 'beat_22_outro_continuation_promise',
    shotId: 'Shot06',
    startFrame: 2260,
    endFrame: 2320,
    vocalStress: 'secondary-stress',
    pitchContour: 'falling-cadence',
    speechCadence: 'ritardando',
    pausePreRollFrames: 8,
    pausePostRollFrames: 10,
    anticipationFrames: 10,
    settleDamping: 0.84,
    scalePeakMultiplier: 1.04,
    velocityRamp: 'smooth-ease',
    materialResponse: {
      rimLightIntensity: 0.50,
      depthShadowBlur: 18,
      frostedBlurPx: 16,
    },
  },
  {
    id: 'prosody_23_master_resolve',
    semanticBeatId: 'beat_23_master_resolve_freeze',
    shotId: 'Shot06',
    startFrame: 2320,
    endFrame: 2361,
    vocalStress: 'pause-cadence',
    pitchContour: 'falling-cadence',
    speechCadence: 'legato',
    pausePreRollFrames: 10,
    pausePostRollFrames: 30,
    anticipationFrames: 0,
    settleDamping: 0.95,
    scalePeakMultiplier: 1.00,
    velocityRamp: 'smooth-ease',
    materialResponse: {
      rimLightIntensity: 0.60,
      depthShadowBlur: 24,
      frostedBlurPx: 20,
    },
  },
];

export function getProsodicBeatById(id: string): ProsodicBeat | undefined {
  return PROSODIC_BEATS.find((b) => b.id === id);
}

export function getProsodicBeatForFrame(frame: number): ProsodicBeat | undefined {
  return PROSODIC_BEATS.find((b) => frame >= b.startFrame && frame < b.endFrame);
}
